window.DONOTTOUCH_PAGE_URL = 'https://npuckett.github.io/p5-phone/doNotTouchWorkshop/';

window.DONOTTOUCH_EXISTING_EXAMPLES = [
  { id: 'orientation-basic', title: 'Orientation', focus: 'Motion range', platform: 'iPhone + Android', description: 'Read rotationX, rotationY, and rotationZ as values you can map to size, color, speed, or position.', link: '../examples/Phone%20Sensor%20Examples/movement/01_orientation_basic/', webEditor: 'https://editor.p5js.org/npuckett/sketches/-_pUgcYmW', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/movement/01_orientation_basic/' },
  { id: 'rotational-velocity', title: 'Rotational Velocity', focus: 'Motion speed', platform: 'iPhone + Android', description: 'Use gyroscope velocity to respond to spinning, twisting, or fast changes in orientation.', link: '../examples/Phone%20Sensor%20Examples/movement/02_rotational_velocity/', webEditor: 'https://editor.p5js.org/npuckett/sketches/fij6LZwPQ', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/movement/02_rotational_velocity/' },
  { id: 'acceleration', title: 'Acceleration', focus: 'Motion force', platform: 'iPhone + Android', description: 'Track acceleration on three axes and turn movement force into an output.', link: '../examples/Phone%20Sensor%20Examples/movement/03_acceleration/', webEditor: 'https://editor.p5js.org/npuckett/sketches/AsM63da8sJ', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/movement/03_acceleration/' },
  { id: 'device-shaken', title: 'Device Shaken', focus: 'Event threshold', platform: 'iPhone + Android', description: 'Use a shake event when you want one clear trigger instead of a continuous value.', link: '../examples/Phone%20Sensor%20Examples/movement/04_device_shaken/', webEditor: 'https://editor.p5js.org/npuckett/sketches/FgraGpDkn', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/movement/04_device_shaken/' },
  { id: 'device-moved', title: 'Device Moved', focus: 'Movement event', platform: 'iPhone + Android', description: 'Use movement thresholds to trigger visuals, sound, or state changes.', link: '../examples/Phone%20Sensor%20Examples/movement/05_device_moved/', webEditor: 'https://editor.p5js.org/npuckett/sketches/0UdVXvdcN', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/movement/05_device_moved/' },
  { id: 'mic-level', title: 'Microphone Level', focus: 'Sound range', platform: 'iPhone + Android', description: 'Turn loudness into a visual value. Good for breath, hum, clap, silence, or fabric muffling experiments.', link: '../examples/Phone%20Sensor%20Examples/microphone/01_mic_level/', webEditor: 'https://editor.p5js.org/npuckett/sketches/fuWalYu-L', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/microphone/01_mic_level/' },
  { id: 'two-tag-effects', title: 'Two Tag Effects', focus: 'NFC event', platform: 'Android Chrome', description: 'Use physical tags as material triggers for different outputs.', link: '../examples/Phone%20Sensor%20Examples/nfc/02_two_tag_effects/', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/nfc/02_two_tag_effects/' },
  { id: 'haptic-feedback', title: 'Haptic Feedback', focus: 'Vibration output', platform: 'Android Chrome', description: 'Use vibration as a physical output when the browser and phone support it.', link: '../examples/Phone%20Sensor%20Examples/vibration/01_haptic_feedback/', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/vibration/01_haptic_feedback/' },
  { id: 'phone-facemesh', title: 'PHONE FaceMesh Two Points', focus: 'Face tracking', platform: 'iPhone + Android', description: 'Track face landmarks and map them correctly onto a phone camera preview.', link: '../examples/ml5/PHONE_FaceMesh_two_points/', webEditor: 'https://editor.p5js.org/npuckett/sketches/DLnD9LIMG', qr: 'https://npuckett.github.io/p5-phone/examples/ml5/PHONE_FaceMesh_two_points/' },
  { id: 'phone-handpose', title: 'PHONE HandPose Two Points', focus: 'Hand tracking', platform: 'iPhone + Android', description: 'Use distances and angles between hand landmarks as interface values.', link: '../examples/ml5/PHONE_HandPose_two_points/', webEditor: 'https://editor.p5js.org/npuckett/sketches/aBF5_M0jN3', qr: 'https://npuckett.github.io/p5-phone/examples/ml5/PHONE_HandPose_two_points/' },
  { id: 'gaze-detector', title: 'Gaze Detector Class', focus: 'Gaze direction', platform: 'iPhone + Android', description: 'Use a small class wrapper to turn face landmarks into gaze values.', link: '../examples/ml5/Gaze_detector_class/', webEditor: 'https://editor.p5js.org/npuckett/sketches/y3aGKwPIx_', qr: 'https://npuckett.github.io/p5-phone/examples/ml5/Gaze_detector_class/' }
];

window.DONOTTOUCH_NEW_EXAMPLES = [
  { id: 'motion-synth', title: 'Motion Synth', focus: 'Motion to sound', platform: 'iPhone + Android', description: 'Map tilt and motion into pitch and volume using generated sound.', link: '../examples/Phone%20Sensor%20Examples/sound/03_motion_synth/', webEditor: 'https://editor.p5js.org/npuckett/sketches/i17rxtwHM', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/sound/03_motion_synth/' },
  { id: 'gif-roll', title: 'Phone and GIF Roll', focus: 'Tilt to animation', platform: 'iPhone + Android', description: 'Map phone rotation to the speed and direction of a GIF-based animation.', link: '../examples/Phone%20and%20Gif/roll/', webEditor: 'https://editor.p5js.org/npuckett/sketches/FgHXAZajKF', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20and%20Gif/roll/' },
  { id: 'breath-bloom', title: 'Breath Bloom', focus: 'Microphone to visuals', platform: 'iPhone + Android', description: 'Use microphone level as a reusable value for bloom size, particle density, and quiet detection.', link: 'examples/01-breath-bloom/', webEditor: 'https://editor.p5js.org/npuckett/sketches/ltew4kojp', qr: 'https://npuckett.github.io/p5-phone/doNotTouchWorkshop/examples/01-breath-bloom/' },
  { id: 'tilt-material-orbit', title: 'Tilt Material Orbit', focus: 'Orientation to motion', platform: 'iPhone + Android', description: 'Tilt the phone to steer orbit radius, rotation speed, and composition without touching the screen.', link: 'examples/02-tilt-material-orbit/', webEditor: 'https://editor.p5js.org/npuckett/sketches/xHgbT2Ad3', qr: 'https://npuckett.github.io/p5-phone/doNotTouchWorkshop/examples/02-tilt-material-orbit/' },
  { id: 'shake-spark-vibration', title: 'Shake Spark Vibration', focus: 'Movement event to output', platform: 'iPhone + Android, vibration on Android', description: 'Shake to trigger sparks and optional vibration, with movement strength stored globally.', link: 'examples/03-shake-spark-vibration/', qr: 'https://npuckett.github.io/p5-phone/doNotTouchWorkshop/examples/03-shake-spark-vibration/' },
  { id: 'mouth-particle-cannon', title: 'Mouth Particle Cannon', focus: 'Face tracking event', platform: 'iPhone + Android', description: 'FaceMesh mouth openness becomes a trigger and a range for particle output.', link: 'examples/04-mouth-particle-cannon/', qr: 'https://npuckett.github.io/p5-phone/doNotTouchWorkshop/examples/04-mouth-particle-cannon/' },
  { id: 'hand-image-opacity', title: 'Hand Image Opacity', focus: 'Hand tracking range', platform: 'iPhone + Android', description: 'Thumb-index distance controls the opacity of an archival image.', link: 'examples/05-hand-image-opacity/', webEditor: 'https://editor.p5js.org/npuckett/sketches/WmjSVSKR1', qr: 'https://npuckett.github.io/p5-phone/doNotTouchWorkshop/examples/05-hand-image-opacity/' }
];