window.DONOTTOUCH_PAGE_URL = 'https://npuckett.github.io/p5-phone/doNotTouchWorkshop/';

window.DONOTTOUCH_EXISTING_EXAMPLES = [
  { id: 'orientation-basic', title: 'Orientation', focus: 'Motion range', description: 'Read rotationX, rotationY, and rotationZ as values you can map to size, color, speed, or position.', capabilities: ['motion', 'orientation'], platforms: ['iOS + Android'], link: '../examples/Phone%20Sensor%20Examples/movement/01_orientation_basic/', webEditor: 'https://editor.p5js.org/npuckett/sketches/-_pUgcYmW', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/movement/01_orientation_basic/' },
  { id: 'rotational-velocity', title: 'Rotational Velocity', focus: 'Motion speed', description: 'Use gyroscope velocity to respond to spinning, twisting, or fast changes in orientation.', capabilities: ['motion', 'gyroscope'], platforms: ['iOS + Android'], link: '../examples/Phone%20Sensor%20Examples/movement/02_rotational_velocity/', webEditor: 'https://editor.p5js.org/npuckett/sketches/fij6LZwPQ', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/movement/02_rotational_velocity/' },
  { id: 'acceleration', title: 'Acceleration', focus: 'Motion force', description: 'Track acceleration on three axes and turn movement force into an output.', capabilities: ['motion', 'accelerometer'], platforms: ['iOS + Android'], link: '../examples/Phone%20Sensor%20Examples/movement/03_acceleration/', webEditor: 'https://editor.p5js.org/npuckett/sketches/AsM63da8sJ', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/movement/03_acceleration/' },
  { id: 'device-shaken', title: 'Device Shaken', focus: 'Event threshold', description: 'Use a shake event when you want one clear trigger instead of a continuous value.', capabilities: ['motion', 'deviceShaken', 'threshold'], platforms: ['iOS + Android'], link: '../examples/Phone%20Sensor%20Examples/movement/04_device_shaken/', webEditor: 'https://editor.p5js.org/npuckett/sketches/FgraGpDkn', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/movement/04_device_shaken/' },
  { id: 'device-moved', title: 'Device Moved', focus: 'Movement event', description: 'Use movement thresholds to trigger visuals, sound, or state changes.', capabilities: ['motion', 'deviceMoved', 'threshold'], platforms: ['iOS + Android'], link: '../examples/Phone%20Sensor%20Examples/movement/05_device_moved/', webEditor: 'https://editor.p5js.org/npuckett/sketches/0UdVXvdcN', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/movement/05_device_moved/' },
  { id: 'mic-level', title: 'Microphone Level', focus: 'Sound range', description: 'Turn loudness into a visual value. Good for breath, hum, clap, silence, or fabric muffling experiments.', capabilities: ['microphone', 'p5.sound'], platforms: ['iOS + Android'], link: '../examples/Phone%20Sensor%20Examples/microphone/01_mic_level/', webEditor: 'https://editor.p5js.org/npuckett/sketches/fuWalYu-L', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/microphone/01_mic_level/' },
  { id: 'two-tag-effects', title: 'Two Tag Effects', focus: 'NFC event', description: 'Use physical tags as material triggers for different outputs.', capabilities: ['nfc', 'aliases'], platforms: ['Android'], link: '../examples/Phone%20Sensor%20Examples/nfc/02_two_tag_effects/', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/nfc/02_two_tag_effects/' },
  { id: 'haptic-feedback', title: 'Haptic Feedback', focus: 'Vibration output', description: 'Use vibration as a physical output when the browser and phone support it.', capabilities: ['vibration', 'touch'], platforms: ['Android'], link: '../examples/Phone%20Sensor%20Examples/vibration/01_haptic_feedback/', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/vibration/01_haptic_feedback/' },
  { id: 'phone-facemesh', title: 'PHONE FaceMesh Two Points', focus: 'Face tracking', description: 'Track face landmarks and map them correctly onto a phone camera preview.', capabilities: ['camera', 'ml5', 'facemesh'], platforms: ['iOS + Android'], link: '../examples/ml5/PHONE_FaceMesh_two_points/', webEditor: 'https://editor.p5js.org/npuckett/sketches/DLnD9LIMG', qr: 'https://npuckett.github.io/p5-phone/examples/ml5/PHONE_FaceMesh_two_points/' },
  { id: 'phone-handpose', title: 'PHONE HandPose Two Points', focus: 'Hand tracking', description: 'Use distances and angles between hand landmarks as interface values.', capabilities: ['camera', 'ml5', 'handpose'], platforms: ['iOS + Android'], link: '../examples/ml5/PHONE_HandPose_two_points/', webEditor: 'https://editor.p5js.org/npuckett/sketches/aBF5_M0jN3', qr: 'https://npuckett.github.io/p5-phone/examples/ml5/PHONE_HandPose_two_points/' },
  { id: 'gaze-detector', title: 'Gaze Detector Class', focus: 'Gaze direction', description: 'Use a small class wrapper to turn face landmarks into gaze values.', capabilities: ['camera', 'ml5', 'facemesh', 'gaze'], platforms: ['iOS + Android'], link: '../examples/ml5/Gaze_detector_class/', webEditor: 'https://editor.p5js.org/npuckett/sketches/y3aGKwPIx_', qr: 'https://npuckett.github.io/p5-phone/examples/ml5/Gaze_detector_class/' }
];

window.DONOTTOUCH_NEW_EXAMPLES = [
  { id: 'motion-synth', title: 'Motion Synth', focus: 'Motion to sound', description: 'Map tilt and motion into pitch and volume using generated sound.', capabilities: ['sound', 'motion', 'p5.sound', 'generated audio'], platforms: ['iOS + Android'], link: '../examples/Phone%20Sensor%20Examples/sound/03_motion_synth/', webEditor: 'https://editor.p5js.org/npuckett/sketches/i17rxtwHM', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/sound/03_motion_synth/' },
  { id: 'gif-roll', title: 'Phone and GIF Roll', focus: 'Tilt to animation', description: 'Map phone rotation to the speed and direction of a GIF-based animation.', capabilities: ['motion', 'gif'], platforms: ['iOS + Android'], link: '../examples/Phone%20and%20Gif/roll/', webEditor: 'https://editor.p5js.org/npuckett/sketches/FgHXAZajKF', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20and%20Gif/roll/' },
  { id: 'camera-color-tracking', title: 'Camera Color Tracking', focus: 'Color match range', description: 'Average the camera color inside a square, tap the square to set the target, and compare with a fixed tolerance.', capabilities: ['camera', 'color', 'tracking'], platforms: ['iOS + Android'], link: '../examples/Phone%20Sensor%20Examples/camera/01_color_tracking/', webEditor: 'https://editor.p5js.org/npuckett/sketches/n9kyBCsHl', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/camera/01_color_tracking/' },
  { id: 'breath-bloom', title: 'Breath Bloom', focus: 'Microphone to visuals', description: 'Use microphone level as a reusable value for bloom size, particle density, and quiet detection.', capabilities: ['microphone', 'p5.sound'], platforms: ['iOS + Android'], link: 'examples/01-breath-bloom/', webEditor: 'https://editor.p5js.org/npuckett/sketches/ltew4kojp', qr: 'https://npuckett.github.io/p5-phone/doNotTouchWorkshop/examples/01-breath-bloom/' },
  { id: 'tilt-material-orbit', title: 'Tilt Material Orbit', focus: 'Orientation to motion', description: 'Tilt the phone to steer orbit radius, rotation speed, and composition without touching the screen.', capabilities: ['motion', 'orientation'], platforms: ['iOS + Android'], link: 'examples/02-tilt-material-orbit/', webEditor: 'https://editor.p5js.org/npuckett/sketches/xHgbT2Ad3', qr: 'https://npuckett.github.io/p5-phone/doNotTouchWorkshop/examples/02-tilt-material-orbit/' },
  { id: 'shake-spark-vibration', title: 'Shake Spark Vibration', focus: 'Movement event to output', description: 'Shake to trigger sparks and optional vibration, with movement strength stored globally.', capabilities: ['motion', 'deviceShaken', 'vibration'], platforms: ['iOS + Android', 'Android'], platformSummary: 'iOS + Android (vibration on Android)', link: 'examples/03-shake-spark-vibration/', qr: 'https://npuckett.github.io/p5-phone/doNotTouchWorkshop/examples/03-shake-spark-vibration/' },
  { id: 'torch-touch-toggle', title: 'Torch Touch Toggle', focus: 'Touch to flashlight', description: 'A direct starter for turning the flashlight on and off with the torch API.', capabilities: ['torch', 'flashlight', 'touch'], platforms: ['iOS + Android'], link: '../examples/Phone%20Sensor%20Examples/torch/01_torch_touch_toggle/', webEditor: 'https://editor.p5js.org/npuckett/sketches/6bBT4VeRa', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/torch/01_torch_touch_toggle/' },
  { id: 'torch-disco', title: 'Torch Disco', focus: 'Light + color + vibration', description: 'Pulse screen color, flashlight, and haptics together at a gentle tempo.', capabilities: ['torch', 'flashlight', 'vibration', 'touch'], platforms: ['iOS + Android', 'Android'], platformSummary: 'iOS + Android (vibration on Android)', link: '../examples/Phone%20Sensor%20Examples/torch/02_torch_disco/', webEditor: 'https://editor.p5js.org/npuckett/sketches/049BpqM9K', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/torch/02_torch_disco/' },
  { id: 'shake-torch-toggle', title: 'Shake Torch Toggle', focus: 'Shake to flashlight', description: 'Use deviceShaken() to toggle the flashlight without touching the screen after setup.', capabilities: ['torch', 'flashlight', 'motion', 'deviceShaken'], platforms: ['iOS + Android'], link: '../examples/Phone%20Sensor%20Examples/torch/03_shake_toggle/', webEditor: 'https://editor.p5js.org/npuckett/sketches/OH_hsgddL', qr: 'https://npuckett.github.io/p5-phone/examples/Phone%20Sensor%20Examples/torch/03_shake_toggle/' },
  { id: 'mouth-particle-cannon', title: 'Mouth Particle Cannon', focus: 'Face tracking event', description: 'FaceMesh mouth openness becomes a trigger and a range for particle output.', capabilities: ['camera', 'ml5', 'facemesh'], platforms: ['iOS + Android'], link: 'examples/04-mouth-particle-cannon/', webEditor: 'https://editor.p5js.org/npuckett/sketches/KQXIYUbuj', qr: 'https://npuckett.github.io/p5-phone/doNotTouchWorkshop/examples/04-mouth-particle-cannon/' },
  { id: 'hand-image-opacity', title: 'Hand Image Opacity', focus: 'Hand tracking range', description: 'Thumb-index distance controls the opacity of an archival image.', capabilities: ['camera', 'ml5', 'handpose'], platforms: ['iOS + Android'], link: 'examples/05-hand-image-opacity/', webEditor: 'https://editor.p5js.org/npuckett/sketches/WmjSVSKR1', qr: 'https://npuckett.github.io/p5-phone/doNotTouchWorkshop/examples/05-hand-image-opacity/' }
];
