window.P5PHONE_EXAMPLES_BASE_URL = 'https://npuckett.github.io/p5-phone/examples/';
window.P5PHONE_GITHUB_BASE_URL = 'https://github.com/npuckett/p5-phone/tree/main/';

window.P5PHONE_EXAMPLES = [
  {
    id: 'blank-template',
    title: 'Blank Template',
    category: 'Start',
    subcategory: 'Starter',
    level: 'Starter',
    p5: '1.x and 2.0',
    description: 'Small baseline sketch for starting a mobile p5-phone project.',
    path: 'blankTemplate/',
    sourcePath: 'examples/blankTemplate',
    webEditor: 'https://editor.p5js.org/creationcomputation/sketches/R-c_HpeUg',
    capabilities: ['setup', 'lockGestures']
  },
  {
    id: 'touch-basic',
    title: 'Basic Touch',
    category: 'Input',
    subcategory: 'Touch',
    level: 'Starter',
    p5: '1.x and 2.0',
    description: 'Detect touch or pointer presses and track duration.',
    path: 'Phone%20Sensor%20Examples/touch/01_touch_basic/',
    minimalPath: 'Phone%20Sensor%20Examples%20-%20Minimal/touch/01_touch_basic/',
    sourcePath: 'examples/Phone%20Sensor%20Examples/touch/01_touch_basic',
    webEditor: 'https://editor.p5js.org/creationcomputation/sketches/zIRMsYKRN',
    capabilities: ['touch']
  },
  {
    id: 'touch-zones',
    title: 'Touch Zones',
    category: 'Input',
    subcategory: 'Touch',
    level: 'Starter',
    p5: '1.x and 2.0',
    description: 'Divide the screen into touchable zones.',
    path: 'Phone%20Sensor%20Examples/touch/02_touch_zones/',
    minimalPath: 'Phone%20Sensor%20Examples%20-%20Minimal/touch/02_touch_zones/',
    sourcePath: 'examples/Phone%20Sensor%20Examples/touch/02_touch_zones',
    webEditor: 'https://editor.p5js.org/creationcomputation/sketches/PkhKKZWMC',
    capabilities: ['touch']
  },
  {
    id: 'touch-count',
    title: 'Touch Count',
    category: 'Input',
    subcategory: 'Touch',
    level: 'Starter',
    p5: '1.x and 2.0',
    description: 'Count simultaneous touch points.',
    path: 'Phone%20Sensor%20Examples/touch/03_touch_count/',
    minimalPath: 'Phone%20Sensor%20Examples%20-%20Minimal/touch/03_touch_count/',
    sourcePath: 'examples/Phone%20Sensor%20Examples/touch/03_touch_count',
    webEditor: 'https://editor.p5js.org/creationcomputation/sketches/g-9HeBb8B',
    capabilities: ['touch']
  },
  {
    id: 'touch-distance',
    title: 'Touch Distance',
    category: 'Input',
    subcategory: 'Touch',
    level: 'Intermediate',
    p5: '1.x and 2.0',
    description: 'Measure the distance between two touch points.',
    path: 'Phone%20Sensor%20Examples/touch/04_touch_distance/',
    minimalPath: 'Phone%20Sensor%20Examples%20-%20Minimal/touch/04_touch_distance/',
    sourcePath: 'examples/Phone%20Sensor%20Examples/touch/04_touch_distance',
    webEditor: 'https://editor.p5js.org/creationcomputation/sketches/s6icb8y_o',
    capabilities: ['touch']
  },
  {
    id: 'touch-angle',
    title: 'Touch Angle',
    category: 'Input',
    subcategory: 'Touch',
    level: 'Intermediate',
    p5: '1.x and 2.0',
    description: 'Calculate an angle between two touch points.',
    path: 'Phone%20Sensor%20Examples/touch/05_touch_angle/',
    minimalPath: 'Phone%20Sensor%20Examples%20-%20Minimal/touch/05_touch_angle/',
    sourcePath: 'examples/Phone%20Sensor%20Examples/touch/05_touch_angle',
    webEditor: 'https://editor.p5js.org/creationcomputation/sketches/IPYIo8_FV',
    capabilities: ['touch']
  },
  {
    id: 'orientation-basic',
    title: 'Orientation',
    category: 'Input',
    subcategory: 'Movement',
    level: 'Starter',
    p5: '1.x and 2.0',
    description: 'Read rotationX, rotationY, and rotationZ from the phone.',
    path: 'Phone%20Sensor%20Examples/movement/01_orientation_basic/',
    minimalPath: 'Phone%20Sensor%20Examples%20-%20Minimal/movement/01_orientation_basic/',
    sourcePath: 'examples/Phone%20Sensor%20Examples/movement/01_orientation_basic',
    webEditor: 'https://editor.p5js.org/creationcomputation/sketches/Sf_um9wYw',
    capabilities: ['motion', 'orientation']
  },
  {
    id: 'rotational-velocity',
    title: 'Rotational Velocity',
    category: 'Input',
    subcategory: 'Movement',
    level: 'Intermediate',
    p5: '1.x and 2.0',
    description: 'Use gyroscope angular velocity to drive visuals.',
    path: 'Phone%20Sensor%20Examples/movement/02_rotational_velocity/',
    minimalPath: 'Phone%20Sensor%20Examples%20-%20Minimal/movement/02_rotational_velocity/',
    sourcePath: 'examples/Phone%20Sensor%20Examples/movement/02_rotational_velocity',
    webEditor: 'https://editor.p5js.org/creationcomputation/sketches/IDSid9rOX',
    capabilities: ['motion', 'gyroscope']
  },
  {
    id: 'acceleration',
    title: 'Acceleration',
    category: 'Input',
    subcategory: 'Movement',
    level: 'Intermediate',
    p5: '1.x and 2.0',
    description: 'Display accelerationX, accelerationY, and accelerationZ data.',
    path: 'Phone%20Sensor%20Examples/movement/03_acceleration/',
    minimalPath: 'Phone%20Sensor%20Examples%20-%20Minimal/movement/03_acceleration/',
    sourcePath: 'examples/Phone%20Sensor%20Examples/movement/03_acceleration',
    webEditor: 'https://editor.p5js.org/creationcomputation/sketches/xaxOYgK9q',
    capabilities: ['motion', 'accelerometer']
  },
  {
    id: 'device-shaken',
    title: 'Device Shaken',
    category: 'Input',
    subcategory: 'Movement',
    level: 'Starter',
    p5: '1.x and 2.0',
    description: 'Use deviceShaken() with setShakeThreshold() to count phone shakes.',
    path: 'Phone%20Sensor%20Examples/movement/04_device_shaken/',
    minimalPath: 'Phone%20Sensor%20Examples%20-%20Minimal/movement/04_device_shaken/',
    sourcePath: 'examples/Phone%20Sensor%20Examples/movement/04_device_shaken',
    capabilities: ['motion', 'deviceShaken', 'threshold']
  },
  {
    id: 'device-moved',
    title: 'Device Moved',
    category: 'Input',
    subcategory: 'Movement',
    level: 'Starter',
    p5: '1.x and 2.0',
    description: 'Use deviceMoved() with setMoveThreshold() to respond to phone movement.',
    path: 'Phone%20Sensor%20Examples/movement/05_device_moved/',
    minimalPath: 'Phone%20Sensor%20Examples%20-%20Minimal/movement/05_device_moved/',
    sourcePath: 'examples/Phone%20Sensor%20Examples/movement/05_device_moved',
    capabilities: ['motion', 'deviceMoved', 'threshold']
  },
  {
    id: 'device-orientation',
    title: 'Device Orientation',
    category: 'Input',
    subcategory: 'Movement',
    level: 'Starter',
    p5: '1.x and 2.0',
    description: 'Use deviceOrientation to detect portrait and landscape phone orientation.',
    path: 'Phone%20Sensor%20Examples/movement/06_device_orientation/',
    minimalPath: 'Phone%20Sensor%20Examples%20-%20Minimal/movement/06_device_orientation/',
    sourcePath: 'examples/Phone%20Sensor%20Examples/movement/06_device_orientation',
    capabilities: ['motion', 'deviceOrientation']
  },
  {
    id: 'mic-level',
    title: 'Microphone Level',
    category: 'Input',
    subcategory: 'Microphone',
    level: 'Starter',
    p5: '1.x and 2.0',
    description: 'Visualize audio input with p5.AudioIn.',
    path: 'Phone%20Sensor%20Examples/microphone/01_mic_level/',
    minimalPath: 'Phone%20Sensor%20Examples%20-%20Minimal/microphone/01_mic_level/',
    sourcePath: 'examples/Phone%20Sensor%20Examples/microphone/01_mic_level',
    webEditor: 'https://editor.p5js.org/creationcomputation/sketches/ySuEk7s6-',
    capabilities: ['microphone', 'p5.sound']
  },
  {
    id: 'speech-recognition',
    title: 'Speech Recognition',
    category: 'Input',
    subcategory: 'Speech',
    level: 'Intermediate',
    p5: '1.x and 2.0',
    description: 'Touch-to-talk speech recognition using the Web Speech API.',
    path: 'Phone%20Sensor%20Examples/microphone/02_speech_recognition/',
    sourcePath: 'examples/Phone%20Sensor%20Examples/microphone/02_speech_recognition',
    capabilities: ['speech', 'microphone']
  },
  {
    id: 'nfc-tag-identifier',
    title: 'NFC Tag Identifier',
    category: 'Input',
    subcategory: 'NFC',
    level: 'Starter',
    p5: '1.x and 2.0',
    description: 'Scan physical NFC tags, name them, and copy IDs into sketches.',
    path: 'Phone%20Sensor%20Examples/nfc/01_nfc_read/',
    sourcePath: 'examples/Phone%20Sensor%20Examples/nfc/01_nfc_read',
    capabilities: ['nfc', 'aliases']
  },
  {
    id: 'nfc-two-tag-effects',
    title: 'Two Tag Effects',
    category: 'Input',
    subcategory: 'NFC',
    level: 'Starter',
    p5: '1.x and 2.0',
    description: 'Use shirt and table aliases in simple if statements.',
    path: 'Phone%20Sensor%20Examples/nfc/02_two_tag_effects/',
    sourcePath: 'examples/Phone%20Sensor%20Examples/nfc/02_two_tag_effects',
    capabilities: ['nfc', 'aliases']
  },
  {
    id: 'sound-basic',
    title: 'Sound Basic',
    category: 'Output',
    subcategory: 'Sound',
    level: 'Starter',
    p5: '1.x and 2.0',
    description: 'Play and pause sound from a touch interaction.',
    path: 'Phone%20Sensor%20Examples/sound/01_dual_audio/',
    minimalPath: 'Phone%20Sensor%20Examples%20-%20Minimal/sound/01_sound_basic/',
    sourcePath: 'examples/Phone%20Sensor%20Examples/sound/01_dual_audio',
    capabilities: ['sound', 'p5.sound']
  },
  {
    id: 'volume-touches',
    title: 'Volume by Touches',
    category: 'Output',
    subcategory: 'Sound',
    level: 'Intermediate',
    p5: '1.x and 2.0',
    description: 'Control audio volume with multiple touches.',
    path: 'Phone%20Sensor%20Examples/sound/02_volume_touches/',
    minimalPath: 'Phone%20Sensor%20Examples%20-%20Minimal/sound/02_sound_amplitude/',
    sourcePath: 'examples/Phone%20Sensor%20Examples/sound/02_volume_touches',
    capabilities: ['sound', 'touch']
  },
  {
    id: 'motion-synth',
    title: 'Motion Synth',
    category: 'Output',
    subcategory: 'Sound',
    level: 'Intermediate',
    p5: '1.x and 2.0',
    description: 'Generate sound with p5.Oscillator and control it with phone motion.',
    path: 'Phone%20Sensor%20Examples/sound/03_motion_synth/',
    minimalPath: 'Phone%20Sensor%20Examples%20-%20Minimal/sound/03_motion_synth/',
    sourcePath: 'examples/Phone%20Sensor%20Examples/sound/03_motion_synth',
    capabilities: ['sound', 'motion', 'p5.sound', 'generated audio']
  },
  {
    id: 'haptic-feedback',
    title: 'Haptic Feedback',
    category: 'Output',
    subcategory: 'Vibration',
    level: 'Starter',
    p5: '1.x and 2.0',
    description: 'Trigger vibration patterns from touch zones on Android.',
    path: 'Phone%20Sensor%20Examples/vibration/01_haptic_feedback/',
    minimalPath: 'Phone%20Sensor%20Examples%20-%20Minimal/vibration/01_haptic_feedback/',
    sourcePath: 'examples/Phone%20Sensor%20Examples/vibration/01_haptic_feedback',
    capabilities: ['vibration', 'touch']
  },
  {
    id: 'ml5-bodypose-phone',
    title: 'PHONE BodyPose Two Points',
    category: 'Input',
    subcategory: 'Camera',
    level: 'Advanced',
    p5: '1.x',
    description: 'BodyPose tracking with PhoneCamera coordinate mapping.',
    path: 'ml5/PHONE_BodyPose_two_points/',
    sourcePath: 'examples/ml5/PHONE_BodyPose_two_points',
    capabilities: ['camera', 'ml5', 'bodypose']
  },
  {
    id: 'ml5-facemesh-phone',
    title: 'PHONE FaceMesh Two Points',
    category: 'Input',
    subcategory: 'Camera',
    level: 'Advanced',
    p5: '1.x',
    description: 'FaceMesh tracking with PhoneCamera coordinate mapping.',
    path: 'ml5/PHONE_FaceMesh_two_points/',
    sourcePath: 'examples/ml5/PHONE_FaceMesh_two_points',
    capabilities: ['camera', 'ml5', 'facemesh']
  },
  {
    id: 'ml5-handpose-phone',
    title: 'PHONE HandPose Two Points',
    category: 'Input',
    subcategory: 'Camera',
    level: 'Advanced',
    p5: '1.x',
    description: 'HandPose tracking with PhoneCamera coordinate mapping.',
    path: 'ml5/PHONE_HandPose_two_points/',
    sourcePath: 'examples/ml5/PHONE_HandPose_two_points',
    capabilities: ['camera', 'ml5', 'handpose']
  },
  {
    id: 'ml5-object-detection-phone',
    title: 'PHONE Object Detection',
    category: 'Input',
    subcategory: 'Camera',
    level: 'Advanced',
    p5: '1.x',
    description: 'COCO-SSD object detection with mapped PhoneCamera bounding boxes.',
    path: 'ml5/PHONE_ObjectDetection/',
    sourcePath: 'examples/ml5/PHONE_ObjectDetection',
    capabilities: ['camera', 'ml5', 'object detection']
  },
  {
    id: 'gaze-detector',
    title: 'Gaze Detector Class',
    category: 'Input',
    subcategory: 'Camera',
    level: 'Advanced',
    p5: '1.x',
    description: 'Reusable gaze tracking class built on ML5 FaceMesh.',
    path: 'ml5/Gaze_detector_class/',
    sourcePath: 'examples/ml5/Gaze_detector_class',
    capabilities: ['camera', 'ml5', 'facemesh']
  },
  {
    id: 'three-bodypose',
    title: 'THREE BodyPose Two Points',
    category: 'Input',
    subcategory: 'Camera',
    level: 'Advanced',
    p5: '1.x',
    description: 'BodyPose data driving a Three.js scene.',
    path: 'ml5/THREE_BodyPose_two_points/',
    sourcePath: 'examples/ml5/THREE_BodyPose_two_points',
    capabilities: ['camera', 'ml5', 'three.js']
  },
  {
    id: 'three-facemesh',
    title: 'THREE FaceMesh Two Points',
    category: 'Input',
    subcategory: 'Camera',
    level: 'Advanced',
    p5: '1.x',
    description: 'FaceMesh data driving a Three.js scene.',
    path: 'ml5/THREE_FaceMesh_two_points/',
    sourcePath: 'examples/ml5/THREE_FaceMesh_two_points',
    capabilities: ['camera', 'ml5', 'three.js']
  },
  {
    id: 'three-handpose',
    title: 'THREE HandPose Two Points',
    category: 'Input',
    subcategory: 'Camera',
    level: 'Advanced',
    p5: '1.x',
    description: 'HandPose data driving a Three.js scene.',
    path: 'ml5/THREE_HandPose_two_points/',
    sourcePath: 'examples/ml5/THREE_HandPose_two_points',
    capabilities: ['camera', 'ml5', 'three.js']
  },
  {
    id: 'ui-banner',
    title: 'Banner Permission Style',
    category: 'Reference',
    subcategory: 'UI Styles',
    level: 'Intermediate',
    p5: '1.x and 2.0',
    description: 'Permission activation from a top or bottom banner.',
    path: 'UIStyles/banner-style/',
    sourcePath: 'examples/UIStyles/banner-style',
    capabilities: ['permission UI']
  },
  {
    id: 'ui-canvas',
    title: 'Canvas Permission Style',
    category: 'Reference',
    subcategory: 'UI Styles',
    level: 'Intermediate',
    p5: '1.x and 2.0',
    description: 'Permission activation through the canvas itself.',
    path: 'UIStyles/canvas-style/',
    sourcePath: 'examples/UIStyles/canvas-style',
    capabilities: ['permission UI']
  },
  {
    id: 'ui-custom-element',
    title: 'Custom Element Permission Style',
    category: 'Reference',
    subcategory: 'UI Styles',
    level: 'Intermediate',
    p5: '1.x and 2.0',
    description: 'Bind permission activation to your own HTML element.',
    path: 'UIStyles/custom-element/',
    sourcePath: 'examples/UIStyles/custom-element',
    capabilities: ['permission UI']
  },
  {
    id: 'gif-fetch',
    title: 'Phone and GIF Fetch',
    category: 'Reference',
    subcategory: 'Phone and GIF',
    level: 'Intermediate',
    p5: '1.x',
    description: 'Combine motion interaction with animated GIF assets.',
    path: 'Phone%20and%20Gif/fetch/',
    sourcePath: 'examples/Phone%20and%20Gif/fetch',
    capabilities: ['motion', 'gif']
  },
  {
    id: 'gif-collision',
    title: 'Phone and GIF Collision',
    category: 'Reference',
    subcategory: 'Phone and GIF',
    level: 'Intermediate',
    p5: '1.x',
    description: 'Motion interaction with simple collision behavior.',
    path: 'Phone%20and%20Gif/collision/',
    sourcePath: 'examples/Phone%20and%20Gif/collision',
    capabilities: ['motion', 'gif']
  },
  {
    id: 'gif-fly',
    title: 'Phone and GIF Fly',
    category: 'Reference',
    subcategory: 'Phone and GIF',
    level: 'Intermediate',
    p5: '1.x',
    description: 'Use phone motion to fly animated GIF elements.',
    path: 'Phone%20and%20Gif/fly/',
    sourcePath: 'examples/Phone%20and%20Gif/fly',
    capabilities: ['motion', 'gif']
  },
  {
    id: 'gif-roll',
    title: 'Phone and GIF Roll',
    category: 'Reference',
    subcategory: 'Phone and GIF',
    level: 'Intermediate',
    p5: '1.x',
    description: 'Use device angle to roll animated GIF elements.',
    path: 'Phone%20and%20Gif/roll/',
    sourcePath: 'examples/Phone%20and%20Gif/roll',
    capabilities: ['motion', 'gif']
  },
  {
    id: 'ux-compare',
    title: 'UX Compare Index',
    category: 'Reference',
    subcategory: 'UX Compare',
    level: 'Advanced',
    p5: '1.x',
    description: 'Comparison demos for traditional UI controls versus phone-native interactions.',
    path: 'UXcompare/',
    sourcePath: 'examples/UXcompare',
    capabilities: ['comparison']
  }
];