name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    
    - name: Install dependencies
      run: npm install --only=dev 2>/dev/null || echo "No dependencies to install"
    
    - name: Run tests
      run: npm test
    
    - name: Validate files
      run: |
        echo "Validating release files..."
        ls -la src/
        test -f src/permissionsAll.js
        test -f src/permissionsGyro.js
        test -f src/permissionMic.js
        test -f src/permissionsGesture.js
        echo "All required files exist ✓"

  create-release:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Changes in this Release
          - See CHANGELOG.md for details
          
          ## CDN Usage
          
          Include in your HTML:
          ```html
          <!-- Touch only -->
          <script src="https://cdn.jsdelivr.net/gh/DigitalFuturesOCADU/mobile-p5-permissions@${{ github.ref_name }}/src/permissionsGesture.js"></script>
          
          <!-- Motion sensors -->
          <script src="https://cdn.jsdelivr.net/gh/DigitalFuturesOCADU/mobile-p5-permissions@${{ github.ref_name }}/src/permissionsGyro.js"></script>
          
          <!-- Microphone -->
          <script src="https://cdn.jsdelivr.net/gh/DigitalFuturesOCADU/mobile-p5-permissions@${{ github.ref_name }}/src/permissionMic.js"></script>
          
          <!-- All permissions -->
          <script src="https://cdn.jsdelivr.net/gh/DigitalFuturesOCADU/mobile-p5-permissions@${{ github.ref_name }}/src/permissionsAll.js"></script>
          ```
        draft: false
        prerelease: false